config/routes.rb
Rails.application.routes.draw do
  root 'browse#index'
  match "browse" => "browse#index", via: [:get]

  get 'welcome/landing'
  #root 'welcome#landing'
  get 'welcome/admin'
  get 'welcome/denied'
  
  
  get 'evidence_sources/my_submissions'
  get 'evidence_sources/new_submitted'
  get 'evidence_sources/rejected'
  get 'evidence_sources/accepted'
  get 'evidence_sources/published'
  get 'evidence_sources/all'

  post 'evidence_sources/research_design'
  post 'evidence_sources/evidence_item'

  resources :evidence_sources do
    resources :g2_evidence_items
  end
  
  get 'headlines/news', to: 'headlines#news'
  post 'headlines/news', to: 'headlines#create_news'
  get 'headlines/recent_articles', to: 'headlines#recent_articles'
  post 'headlines/recent_articles', to: 'headlines#create_recent_articles'

  get "search/history"
  resources :search do
  end

  resources :methodologies
  resources :se_methods
  # resources :evidence_items
  resources :research_methods
  resources :participants
  resources :notifications
  resources :news
  resources :papers
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/search.rb
class Search < ApplicationRecord
  has_many :search_fields,:dependent=> :destroy
  accepts_nested_attributes_for :search_fields, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_search, only: [:index]
  before_action :set_search_conditions, only: [:show]
  skip_before_action :authenticate_user!

  def index
  end

  def create
    @search = Search.new()
    @search.name = search_params[:name] if search_params[:name]

    fields_params.keys.each do |key|
      fields = fields_params[key]
      fields.delete_if {|x| x.to_s == "_destroy" }
      @search.search_fields.build(fields)
    end

    if @search.save!
      render json: {success: true}
    else
      render json: {success: false}, status: 400
    end
  end

  def history
    @searches = Search.all
  end

  def show
  end

  private
  def search_params
    if params.include?(:search)
      params.require(:search).permit(:id, :from_date, :to_date, :name, :saved_on,
                                     :search_fields_attributes => [:content,:field,:op1,:op2,:_destroy]);
    else
      params.permit(:id)
    end
  end

  def fields_params
    search_params[:search_fields_attributes]
  end

  def set_search
    if search_params[:search_fields_attributes]
      @search = Search.new(search_params)

      if(@search.search_fields.blank?)
        @search.search_fields.build(search_params[:search_fields_attributes][0])
      end

      #search_scope = make_query params
      #@results = search_scope.call(EvidenceSource)
      set_search_conditions
    else
      @search = Search.new
      if @search.search_fields.blank?
        @search.search_fields.build
      end
      @results = []
    end
  end

  def set_search_conditions
    if search_params[:id]
      @search = Search.find(search_params[:id])
    else
      @search = Search.new(search_params)
    end

    query_string = ""
    query_author = false

    @search.search_fields.each do |search_field|
      unless search_field.content.blank?
        query_string << "#{search_field.op1} " unless query_string.blank?
        query_string << "#{search_field.field} "
        query_string << "#{search_field.op2} "

        query_author = true if search_field.field == "name" or search_field.field == "name_abbr"

        if search_field.op2 == "=" || search_field.op2 == ">" || search_field.op2 == "<"
          query_string << "'#{search_field.content}' "
        else
          query_string << "'%#{search_field.content}%' "
        end
      end
    end

    unless @search.from_date.blank?
      query_string << "AND " unless query_string.blank?
      query_string << "published_time >= "
      query_string << "'#{@search.from_date}' "
    end

    unless @search.to_date.blank?
      query_string << "AND " unless query_string.blank?
      query_string << "published_time <= "
      query_string << "'#{@search.to_date}' "
    end

    scope_proc = search_scope(query_string, query_author)
    @results = scope_proc.call(EvidenceSource)
  end

  def sort_column
    return params[:sort] if params[:sort] == "name"

    EvidenceSource.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

  #make query string for PG
  def make_query params
    query_string = String.new
    query_author = false
    #Geting Date

    items = params[:search][:search_fields_attributes].values
    items.each do |search_field|
      unless search_field[:content].blank?
        field = search_field[:field]
        query_string << "#{search_field[:op1]} " unless query_string.blank?
        query_string << "#{field} "
        query_string << "#{search_field[:op2]} "

        query_author = true if field == "name" or field == "name_abbr"

        if search_field[:op2] == "=" || search_field[:op2] == ">" || search_field[:op2] == "<"
          query_string << "'#{search_field[:content]}' "
        else
          query_string << "'%#{search_field[:content]}%' "
        end
      end
    end

    unless params[:search][:from_date].blank?
      query_string << "AND " unless query_string.blank?
      query_string << "published_time >= "
      query_string << "'#{params[:search][:from_date]}' "
    end

    unless params[:search][:to_date].blank?
      query_string << "AND " unless query_string.blank?
      query_string << "published_time <= "
      query_string << "'#{params[:search][:to_date]}' "
    end

    search_scope(query_string, query_author)
  end

  def search_scope(query_string, query_author=false)
    hash = {sort_column.to_sym => sort_direction.to_sym}
    if query_author
      -> (model) { model.joins(:evidence_source_authors).where(query_string).order(hash)}
    elsif sort_column == "name"
      -> (model) { model.joins(:evidence_source_authors).where(query_string).order("evidence_source_authors.#{sort_column} #{sort_direction}")}
    else
      -> (model) { model.where(query_string).order(hash)}
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def sort_link(title, column)
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, "#", :"data-sort" => column, :"data-direction" => direction, :class => css_class
  end
end

app/views/search/_left_search_form.html.erb
      <dl class="row">
        <dt><strong> <%=label :from_date, 'From: ', html: {class: "col-sm-2 col-md-2"} %></strong></dt>
        <dd class="input-group date col-sm-6 col-md-8" id="fromdate">
        <%=f.text_field :from_date, value: @search.from_date, class: 'form-control' %>
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
        </dd>
      </dl>

      <dl class="row">
        <dt><strong> <%= label_tag :to_date, 'To:', html: {class: "col-sm-2 col-md-2"} %> </strong></dt>
        <dd class="input-group date col-sm-6 col-md-8" id="todate">
        <%=f.text_field :to_date, value: @search.to_date, class: 'form-control' %>
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
        </dd>
      </dl>

      <dl class="row">
        <dt></dt>
        <dd>
        <%= f.submit "Search", class: "btn btn-info btn-sm" %>
        </dd>
      </dl>

app/views/search/_popup.html.erb
<div class="modal fade" id="invalid_pop" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">Invalid Input</h4>
      </div>
      <div class="modal-body">
        Sorry, Invalid input, Try to input value again...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/search/_results.html.erb
<h4>Search Result: <%= @results.count if @result%> </h4>

<table class="table">
  <thead>
    <tr>
      <td class="title_header"><%= sort_link "Title", "title" %></td>
      <td class="name_header"><%= sort_link "Authors", "name" %></td>
      <td class="year_header"><%= sort_link "Year", "year" %></td>
      <td class="source_title_header"><%= sort_link "Source", "source_title" %></td>
      <td class="research_aim_header"><%= sort_link "Research Aim", "research_aim"%></td>
      <td class="publisher_header"><%= sort_link "Publisher", "publisher"%></td>
      <td class="published_time_header"><%= sort_link "Published At", "published_time"%></td>
      <td class="doi_header"><%= sort_link "DOI", "doi"%></td>
    </tr>
  </thead>
  <tbody>
    <% @results.each_with_index do |evidence, index| %>
      <tr>
        <td class="title_header"> <%= evidence.title %> </td>
        <td class="name_header"> <%= evidence.authors %>  </td>
        <td class="year_header"> <%= evidence.year %> </td>
        <td class="source_title_header"> <%= evidence.source_title %>  </td>
        <td class="research_aim_header"> <%= evidence.research_aim %> </td>
        <td class="publisher_header"> <%= evidence.publisher %> </td>
        <td class="published_time_header"> <%= evidence.published_time%> </td>
        <td class="doi_header"> <%= evidence.DOI %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/search/_save_search.html.erb
<div class="modal fade" id="save_search_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Save Current Search</h4>
      </div>
      <div class="modal-body">
        <div class="form-group row">
          <%= f.label "Search Name:", class: "col-sm-5 control-label"%>
          <div class="col-sm-4 col-md-4">
          <%= f.text_field :name, size: 30,:id=>"saved_search_name" ,class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= link_to "Save", "#",:id=>'save_search_link' ,:class => "btn btn-primary", :"data-action" => "save" %>
      </div>
    </div>
  </div>
</div>

app/views/search/_search_form.erb
<% init = true %>
<%= nested_form_for(@search, url: search_index_path,
                    :html => { :id=> "search_form",:method => 'GET',:class => "form-inline search_form" }) do |f| %>
                    <input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token" />
                    <%=f.fields_for :search_fields,nil,{ :class => 'search_fields'} do |builder|  %>
                      <div class ="search_field">

                        <%unless init == true %>
                          <%= builder.select :op1,
                            options_for_select([["OR", "or" ], ["AND", "and"]], builder.object[:op1]),
                            {},{:class=>"form-control"}

                          %>
                      <%end%>

                      <%= builder.select :field, options_for_select([["Source Title", "source_title" ],
                                                                     ["Author", "name"],
                                                                     ["Author Abbr.", "name_abbr"],
                                                                     ["Category","category"],
                                                                     ["Publisher","publisher"],
                                                                     ["URL","URL"],
                                                                     ["DOI","DOI"],
                                                                     ["Research Aim","research_aim"],
                                                                     ["Year","year"],
                                                                     ["Raw Bib","raw_bib"],
                                                                     ["Raw APA","raw_apa"],
                      ],
                      builder.object[:field]),
                      {},{:class=>"form-control search_field_option"}

                    %>

                  <%= builder.select :op2,
                    options_for_select([["Contain", "ILIKE" ],
                                        ["Does not contain", "NOT ILIKE"],
                                        ["Is equal to", "="],
                                        ["Is less than", "<"],
                                        ["Is more than", ">"],
                  ],
                  builder.object[:op2]) ,
                    {},:class=>"form-control search_operation"

                  %>

                <%= builder.text_field :content,:class=>"form-control",:autofocus=>true %>


                <% unless init == true %>
                  <%= builder.link_to_remove "Remove Field",:class => 'btn btn-danger btn-sm'%>
                <%end%>
                <% init = false%>
                      </div>
                    <% end %>

                    <div class="button-group">
                      <%= f.link_to_add "Add a Field", :search_fields,:class => 'btn btn-info btn-sm' %>
                      <%= f.submit "Search", class: "btn btn-info btn-sm" %>
                      <%= link_to "Clear", search_index_path, class: "btn btn-default btn-sm" %>
                      <button type="button" class="btn btn-primary btn-sm" id="save_search_btn"data-toggle="modal" data-target="#save_search_modal">
                        Save Search
                      </button>
                      <%= link_to "Search History", search_history_path,:id=>'search_history' %>
                    </div>

                    <div class="columns-select">

                      <select multiple="multiple" id="columns_select" name="columns_select">
                        <option value="title" selected="selected">Title</option>
                        <option value="name"  selected="selected">Authors</option>
                        <option value="year" selected="selected">Year</option>
                        <option value="source_title" selected="selected">Source</option>
                        <option value="research_aim" selected="selected">Research Aim</option>
                        <option value="publisher" selected="selected">Publisher</option>
                        <option value="published_time" selected="selected">Published At</option>
                        <option value="doi" selected="selected">DOI</option>
                      </select>
                    </div>

                    <div class="container">
                      <div class="row results">
                        <div class="left col-sm-2 col-md-2">
                          <%= render 'left_search_form', f: f %>
                        </div>
                        <div class="right col-sm-10 col-md-10">
                          <div class="table-responsive">
                            <%= render 'results' if @results%>
                          </div>
                        </div>
                      </div>
                    </div>
                    <%= render 'save_search', f: f %>
                  <% end %>


                  <%= render 'popup'%>

app/views/search/history.html.erb
<div class="container">
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <td>#</td>
          <td>Name</td>
          <td>Conditions</td>
          <td>Created At</td>
          <td></td>
        </tr>
      </thead>
      <tbody>
        <% @searches.each_with_index do |search, index| %>
          <tr>
            <td> <%= index %> </td>
            <td> <%= search.name %> </td>
            <td>
              <% search.search_fields.each_with_index do |field, index| %>
                <p>
                <%= "#{field.op1} #{field.field} #{field.op2} #{field.content}" %>
                </p>
              <% end %>
            </td>
            <td>
              <%= search.created_at.strftime("%v") %>
            </td>
            <td>
              <%= link_to "Execute Search", search_path(search), :class => "btn btn-primary btn-sm" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/search/index.html.erb
<div class="container">
<h1>Library Search</h1>
  <%= render "search_form"%>
</div>

app/views/search/show.html.erb
<div class="container">
  <div class="table-responsive">
    <%= render "results" %>
  </div>
</div>