config/routes.rb
Rails.application.routes.draw do
  root 'browse#index'
  match "browse" => "browse#index", via: [:get]

  get 'welcome/landing'
  #root 'welcome#landing'
  get 'welcome/admin'
  get 'welcome/denied'
  
  
  get 'evidence_sources/my_submissions'
  get 'evidence_sources/new_submitted'
  get 'evidence_sources/rejected'
  get 'evidence_sources/accepted'
  get 'evidence_sources/published'
  get 'evidence_sources/all'

  post 'evidence_sources/research_design'
  post 'evidence_sources/evidence_item'

  resources :evidence_sources do
    resources :g2_evidence_items
  end
  
  get 'headlines/news', to: 'headlines#news'
  post 'headlines/news', to: 'headlines#create_news'
  get 'headlines/recent_articles', to: 'headlines#recent_articles'
  post 'headlines/recent_articles', to: 'headlines#create_recent_articles'

  get "search/history"
  resources :search do
  end

  resources :methodologies
  resources :se_methods
  # resources :evidence_items
  resources :research_methods
  resources :participants
  resources :notifications
  resources :news
  resources :papers
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :user
    else
      can :read, :all
    end
  end
end

app/models/evidence_item.rb
class EvidenceItem < ApplicationRecord
  belongs_to :paper
  has_and_belongs_to_many :se_methods
end

app/models/evidence_source.rb
class EvidenceSource < ApplicationRecord
    has_many :evidence_source_authors, dependent: :destroy

    def authors
      author_names = self.evidence_source_authors.collect { |e| e.name }

      return author_names.join(", ") if author_names
      ""
    end
end

app/models/g2_evidence_item.rb
class G2EvidenceItem < ApplicationRecord
    has_and_belongs_to_many :se_methods, join_table: :g2_evidence_item_method
end

app/models/methodology.rb
class Methodology < ApplicationRecord
  has_many :se_methods
end

app/models/news.rb
class News < ApplicationRecord
  has_many :notifications
  has_many :users, through: :notifications
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :news
end

app/models/paper.rb
class Paper < ApplicationRecord
  has_many :evidence_items
  belongs_to :user
  has_and_belongs_to_many :participants
  has_and_belongs_to_many :research_methods
end

app/models/participant.rb
class Participant < ApplicationRecord
  has_and_belongs_to_many :papers
end

app/models/research_design.rb
class ResearchDesign < ApplicationRecord
end

app/models/research_method.rb
class ResearchMethod < ApplicationRecord
  has_and_belongs_to_many :papers
end

app/models/se_method.rb
class SeMethod < ApplicationRecord
  belongs_to :methodology
  has_and_belongs_to_many :g2_evidence_items, join_table: :g2_evidence_item_method
end

app/models/search.rb
class Search < ApplicationRecord
  has_many :search_fields,:dependent=> :destroy
  accepts_nested_attributes_for :search_fields, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/search_field.rb
class SearchField < ApplicationRecord
  #attr_accessor :search_id, :content, :field, :op1, :op2
  belongs_to :search

end

app/models/user.rb
class User < ApplicationRecord

  has_many :papers
  has_many :notifications
  has_many :news, through: :notifications

  validates :first_name, presence: true
  validates :middle_name, presence: true
  validates :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ROLES = %i[user moderator analyst administrator]

  def roles=(roles)
    roles = [*roles].map { |r| r.to_sym }
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def has_role?(role)
    ROLES.include?(role)
  end
  
  def check_role?(role)
    puts 'xxxxxxxxxxxxxxx'
    puts roles_mask
    puts 2**ROLES.index(role)
    not ((roles_mask.to_i || 0) & 2**ROLES.index(role)).zero?
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:user_id, :news_id)
    end
end

app/helpers/browse_helper.rb
module BrowseHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/se_methods_helper.rb
module SeMethodsHelper
end

app/helpers/search_helper.rb
module SearchHelper
  def sort_link(title, column)
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, "#", :"data-sort" => column, :"data-direction" => direction, :class => css_class
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/notifications/_form.html.erb
<%= form_for(notification) do |f| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :news_id %>
    <%= f.number_field :news_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>News</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.user_id %></td>
        <td><%= notification.news_id %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @notification.user_id %>
</p>

<p>
  <strong>News:</strong>
  <%= @notification.news_id %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>