config/routes.rb
Rails.application.routes.draw do
  root 'browse#index'
  match "browse" => "browse#index", via: [:get]

  get 'welcome/landing'
  #root 'welcome#landing'
  get 'welcome/admin'
  get 'welcome/denied'
  
  
  get 'evidence_sources/my_submissions'
  get 'evidence_sources/new_submitted'
  get 'evidence_sources/rejected'
  get 'evidence_sources/accepted'
  get 'evidence_sources/published'
  get 'evidence_sources/all'

  post 'evidence_sources/research_design'
  post 'evidence_sources/evidence_item'

  resources :evidence_sources do
    resources :g2_evidence_items
  end
  
  get 'headlines/news', to: 'headlines#news'
  post 'headlines/news', to: 'headlines#create_news'
  get 'headlines/recent_articles', to: 'headlines#recent_articles'
  post 'headlines/recent_articles', to: 'headlines#create_recent_articles'

  get "search/history"
  resources :search do
  end

  resources :methodologies
  resources :se_methods
  # resources :evidence_items
  resources :research_methods
  resources :participants
  resources :notifications
  resources :news
  resources :papers
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :user
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evidence_item.rb
class EvidenceItem < ApplicationRecord
  belongs_to :paper
  has_and_belongs_to_many :se_methods
end

app/models/evidence_source.rb
class EvidenceSource < ApplicationRecord
    has_many :evidence_source_authors, dependent: :destroy

    def authors
      author_names = self.evidence_source_authors.collect { |e| e.name }

      return author_names.join(", ") if author_names
      ""
    end
end

app/models/g2_evidence_item.rb
class G2EvidenceItem < ApplicationRecord
    has_and_belongs_to_many :se_methods, join_table: :g2_evidence_item_method
end

app/models/methodology.rb
class Methodology < ApplicationRecord
  has_many :se_methods
end

app/models/news.rb
class News < ApplicationRecord
  has_many :notifications
  has_many :users, through: :notifications
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :news
end

app/models/paper.rb
class Paper < ApplicationRecord
  has_many :evidence_items
  belongs_to :user
  has_and_belongs_to_many :participants
  has_and_belongs_to_many :research_methods
end

app/models/participant.rb
class Participant < ApplicationRecord
  has_and_belongs_to_many :papers
end

app/models/research_design.rb
class ResearchDesign < ApplicationRecord
end

app/models/research_method.rb
class ResearchMethod < ApplicationRecord
  has_and_belongs_to_many :papers
end

app/models/se_method.rb
class SeMethod < ApplicationRecord
  belongs_to :methodology
  has_and_belongs_to_many :g2_evidence_items, join_table: :g2_evidence_item_method
end

app/models/search.rb
class Search < ApplicationRecord
  has_many :search_fields,:dependent=> :destroy
  accepts_nested_attributes_for :search_fields, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/search_field.rb
class SearchField < ApplicationRecord
  #attr_accessor :search_id, :content, :field, :op1, :op2
  belongs_to :search

end

app/models/user.rb
class User < ApplicationRecord

  has_many :papers
  has_many :notifications
  has_many :news, through: :notifications

  validates :first_name, presence: true
  validates :middle_name, presence: true
  validates :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ROLES = %i[user moderator analyst administrator]

  def roles=(roles)
    roles = [*roles].map { |r| r.to_sym }
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def has_role?(role)
    ROLES.include?(role)
  end
  
  def check_role?(role)
    puts 'xxxxxxxxxxxxxxx'
    puts roles_mask
    puts 2**ROLES.index(role)
    not ((roles_mask.to_i || 0) & 2**ROLES.index(role)).zero?
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url, notice: 'Paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:paper_id, :user_id, :paper_status, :moderator_id, :moderated_time, :analyst_id, :analysed_time, :authors, :title, :journal, :year, :volume, :pages, :month, :credibility_rate, :research_metrix, :research_aim)
    end
end

app/helpers/browse_helper.rb
module BrowseHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/se_methods_helper.rb
module SeMethodsHelper
end

app/helpers/search_helper.rb
module SearchHelper
  def sort_link(title, column)
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, "#", :"data-sort" => column, :"data-direction" => direction, :class => css_class
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/papers/_form.html.erb
<%= form_for(paper) do |f| %>
  <% if paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :paper_id %>
    <%= f.text_field :paper_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :paper_status %>
    <%= f.number_field :paper_status %>
  </div>

  <div class="field">
    <%= f.label :moderator_id %>
    <%= f.number_field :moderator_id %>
  </div>

  <div class="field">
    <%= f.label :moderated_time %>
    <%= f.datetime_select :moderated_time %>
  </div>

  <div class="field">
    <%= f.label :analyst_id %>
    <%= f.number_field :analyst_id %>
  </div>

  <div class="field">
    <%= f.label :analysed_time %>
    <%= f.datetime_select :analysed_time %>
  </div>

  <div class="field">
    <%= f.label :authors %>
    <%= f.text_area :authors %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :journal %>
    <%= f.text_area :journal %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.text_area :year %>
  </div>

  <div class="field">
    <%= f.label :volume %>
    <%= f.text_area :volume %>
  </div>

  <div class="field">
    <%= f.label :pages %>
    <%= f.text_area :pages %>
  </div>

  <div class="field">
    <%= f.label :month %>
    <%= f.text_area :month %>
  </div>

  <div class="field">
    <%= f.label :credibility_rate %>
    <%= f.number_field :credibility_rate %>
  </div>

  <div class="field">
    <%= f.label :research_metrix %>
    <%= f.text_area :research_metrix %>
  </div>

  <div class="field">
    <%= f.label :research_aim %>
    <%= f.text_area :research_aim %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Papers</h1>

<table>
  <thead>
    <tr>
      <th>Paper</th>
      <th>User</th>
      <th>Paper status</th>
      <th>Moderator</th>
      <th>Moderated time</th>
      <th>Analyst</th>
      <th>Analysed time</th>
      <th>Authors</th>
      <th>Title</th>
      <th>Journal</th>
      <th>Year</th>
      <th>Volume</th>
      <th>Pages</th>
      <th>Month</th>
      <th>Credibility rate</th>
      <th>Research metrix</th>
      <th>Research aim</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td><%= paper.paper_id %></td>
        <td><%= paper.user_id %></td>
        <td><%= paper.paper_status %></td>
        <td><%= paper.moderator_id %></td>
        <td><%= paper.moderated_time %></td>
        <td><%= paper.analyst_id %></td>
        <td><%= paper.analysed_time %></td>
        <td><%= paper.authors %></td>
        <td><%= paper.title %></td>
        <td><%= paper.journal %></td>
        <td><%= paper.year %></td>
        <td><%= paper.volume %></td>
        <td><%= paper.pages %></td>
        <td><%= paper.month %></td>
        <td><%= paper.credibility_rate %></td>
        <td><%= paper.research_metrix %></td>
        <td><%= paper.research_aim %></td>
        <td><%= link_to 'Show', paper %></td>
        <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
        <td><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paper', new_paper_path %>

app/views/papers/new.html.erb
<h1>New Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Paper:</strong>
  <%= @paper.paper_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @paper.user_id %>
</p>

<p>
  <strong>Paper status:</strong>
  <%= @paper.paper_status %>
</p>

<p>
  <strong>Moderator:</strong>
  <%= @paper.moderator_id %>
</p>

<p>
  <strong>Moderated time:</strong>
  <%= @paper.moderated_time %>
</p>

<p>
  <strong>Analyst:</strong>
  <%= @paper.analyst_id %>
</p>

<p>
  <strong>Analysed time:</strong>
  <%= @paper.analysed_time %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @paper.authors %>
</p>

<p>
  <strong>Title:</strong>
  <%= @paper.title %>
</p>

<p>
  <strong>Journal:</strong>
  <%= @paper.journal %>
</p>

<p>
  <strong>Year:</strong>
  <%= @paper.year %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @paper.volume %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @paper.pages %>
</p>

<p>
  <strong>Month:</strong>
  <%= @paper.month %>
</p>

<p>
  <strong>Credibility rate:</strong>
  <%= @paper.credibility_rate %>
</p>

<p>
  <strong>Research metrix:</strong>
  <%= @paper.research_metrix %>
</p>

<p>
  <strong>Research aim:</strong>
  <%= @paper.research_aim %>
</p>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>